import { Component } from '@angular/core';
import {ActivatedRoute} from "@angular/router";

@Component({
  selector: 'app-categories',
  templateUrl: 'categories.component.html',
  styleUrls: ['categories.component.css']
})
export class CategoriesComponent {
  cat: any;
  products: any = [
    {id: 'cafesuada-dacbiet', category: 'cafe', title: 'Cà phê sữa đá đặc biệt', price: 39000, description: 'Thức uống giúp tỉnh táo tức thì để bắt đầu ngày mới thật hứng khởi. Không đắng khét như cà phê truyền thống, Cà phê sữa đá đặc biệt mang hương vị hài hoà đầy lôi cuốn. Là sự đậm đà của 100% cà phê Arabica Cầu Đất rang vừa tới, biến tấu tinh tế với sữa đặc và kem sữa ngọt ngào cực quyến rũ. Càng hấp dẫn hơn với topping thạch 100% cà phê nguyên chất giúp giữ trọn vị ngon đến ngụm cuối cùng.', img: 'assets/images/cafesuada-dacbiet.webp'},
    {id: 'cafesua-da', category: 'cafe', title: 'Cà phê sữa đá', price: 29000, description: 'Cà phê Đắk Lắk nguyên chất được pha phin truyền thống kết hợp với sữa đặc tạo nên hương vị đậm đà, hài hòa giữa vị ngọt đầu lưỡi và vị đắng thanh thoát nơi hậu vị.', img: 'assets/images/cafesua-da.jpg'},
    {id: 'cafesua-nong', category: 'cafe', title: 'Cà Phê Sữa Nóng', price: 35000, description: 'Cà phê được pha phin truyền thống kết hợp với sữa đặc tạo nên hương vị đậm đà, hài hòa giữa vị ngọt đầu lưỡi và vị đắng thanh thoát nơi hậu vị.', img: 'assets/images/cafesua-nong.jpg'},
    {id: 'bacsiu', category: 'cafe', title: 'Bạc Sỉu', price: 29000, description: 'Bạc sỉu chính là "Ly sữa trắng kèm một chút cà phê". Thức uống này rất phù hợp những ai vừa muốn trải nghiệm chút vị đắng của cà phê vừa muốn thưởng thức vị ngọt béo ngậy từ sữa.', img: 'assets/images/bacsiu.jpg'},
    {id: 'bacsiu-nong', category: 'cafe', title: 'Bạc Sỉu Nóng', price: 35000, description: 'Bạc sỉu chính là "Ly sữa trắng kèm một chút cà phê". Thức uống này rất phù hợp những ai vừa muốn trải nghiệm chút vị đắng của cà phê vừa muốn thưởng thức vị ngọt béo ngậy từ sữa.', img: 'assets/images/bacsiu-nong.jpg'},
    {id: 'cafeden-da', category: 'cafe', title: 'Cà Phê Đen Đá', price: 29000, description: 'Không ngọt ngào như Bạc sỉu hay Cà phê sữa, Cà phê đen mang trong mình phong vị trầm lắng, thi vị hơn. Người ta thường phải ngồi rất lâu mới cảm nhận được hết hương thơm ngào ngạt, phảng phất mùi cacao và cái đắng mượt mà trôi tuột xuống vòm họng.', img: 'assets/images/cafeden-da.jpg'},
    {id: 'cafeden-nong', category: 'cafe', title: 'Cà Phê Đen Nóng', price: 35000, description: 'Không ngọt ngào như Bạc sỉu hay Cà phê sữa, Cà phê đen mang trong mình phong vị trầm lắng, thi vị hơn. Người ta thường phải ngồi rất lâu mới cảm nhận được hết hương thơm ngào ngạt, phảng phất mùi cacao và cái đắng mượt mà trôi tuột xuống vòm họng.', img: 'assets/images/cafeden-nong.jpg'},
    {id: 'caramelmacchiato-da', category: 'cafe', title: 'Caramel Macchiato Đá', price: 49000, description: 'Caramel Macchiato sẽ mang đến một sự ngạc nhiên thú vị khi vị thơm béo của bọt sữa, sữa tươi, vị đắng thanh thoát của cà phê Espresso hảo hạng và vị ngọt đậm của sốt caramel được gói gọn trong một tách cà phê.', img: 'assets/images/caramelmacchiato-da.webp'},
    {id: 'caramelmacchiato-nong', category: 'cafe', title: 'Caramel Macchiato (N)', price: 49000, description: 'Caramel Macchiato sẽ mang đến một sự ngạc nhiên thú vị khi vị thơm béo của bọt sữa, sữa tươi, vị đắng thanh thoát của cà phê Espresso hảo hạng và vị ngọt đậm của sốt caramel được gói gọn trong một tách cà phê.', img: 'assets/images/caramelmacchiato-nong.jpg'},
    {id: 'latte-da', category: 'cafe', title: 'Latte Đá', price: 49000, description: 'Một sự kết hợp tinh tế giữa vị đắng cà phê Espresso nguyên chất hòa quyện cùng vị sữa nóng ngọt ngào, bên trên là một lớp kem mỏng nhẹ tạo nên một tách cà phê hoàn hảo về hương vị lẫn nhãn quan.', img: 'assets/images/latte-da.webp'},
    {id: 'latte-nong', category: 'cafe', title: 'Latte Nóng', price: 49000, description: 'Một sự kết hợp tinh tế giữa vị đắng cà phê Espresso nguyên chất hòa quyện cùng vị sữa nóng ngọt ngào, bên trên là một lớp kem mỏng nhẹ tạo nên một tách cà phê hoàn hảo về hương vị lẫn nhãn quan.', img: 'assets/images/latte-nong.webp'},
    {id: 'americano-da', category: 'cafe', title: 'Americano Đá', price: 39000, description: 'Americano được pha chế bằng cách pha thêm nước với tỷ lệ nhất định vào tách cà phê Espresso, từ đó mang lại hương vị nhẹ nhàng và giữ trọn được mùi hương cà phê đặc trưng.', img: 'assets/images/americano-da.webp'},
    {id: 'americano-nong', category: 'cafe', title: 'Americano Nóng', price: 39000, description: 'Americano được pha chế bằng cách pha thêm nước với tỷ lệ nhất định vào tách cà phê Espresso, từ đó mang lại hương vị nhẹ nhàng và giữ trọn được mùi hương cà phê đặc trưng.', img: 'assets/images/americano-nong.webp'},
    {id: 'capuchino-da', category: 'cafe', title: 'Cappuccino Đá', price: 49000, description: 'Capuchino là thức uống hòa quyện giữa hương thơm của sữa, vị béo của bọt kem cùng vị đậm đà từ cà phê Espresso. Tất cả tạo nên một hương vị đặc biệt, một chút nhẹ nhàng, trầm lắng và tinh tế.', img: 'assets/images/capuchino-da.webp'},
    {id: 'capuchino-nong', category: 'cafe', title: 'Cappuccino Nóng', price: 49000, description: 'Capuchino là thức uống hòa quyện giữa hương thơm của sữa, vị béo của bọt kem cùng vị đậm đà từ cà phê Espresso. Tất cả tạo nên một hương vị đặc biệt, một chút nhẹ nhàng, trầm lắng và tinh tế.', img: 'assets/images/capuchino-nong.webp'},
    {id: 'espresso-da', category: 'cafe', title: 'Espresso Đá', price: 45000, description: 'Một tách Espresso nguyên bản được bắt đầu bởi những hạt Arabica chất lượng, phối trộn với tỉ lệ cân đối hạt Robusta, cho ra vị ngọt caramel, vị chua dịu và sánh đặc.', img: 'assets/images/espresso-da.webp'},
    {id: 'espresso-nong', category: 'cafe', title: 'Espresso Nóng', price: 39000, description: 'Một tách Espresso nguyên bản được bắt đầu bởi những hạt Arabica chất lượng, phối trộn với tỉ lệ cân đối hạt Robusta, cho ra vị ngọt caramel, vị chua dịu và sánh đặc.', img: 'assets/images/espresso-nong.webp'},
    {id: 'coldbrew-phucbontu', category: 'cafe', title: 'Cold Brew Phúc Bồn Tử', price: 45000, description: 'Vị chua ngọt của trái phúc bồn tử, làm dậy lên hương vị trái cây tự nhiên vốn sẵn có trong hạt cà phê, hòa quyện thêm vị đăng đắng, ngọt dịu nhẹ nhàng của Cold Brew 100% hạt Arabica Cầu Đất để mang đến một cách thưởng thức cà phê hoàn toàn mới, vừa thơm lừng hương cà phê quen thuộc, vừa nhẹ nhàng và thanh mát bởi hương trái cây đầy thú vị.', img: 'assets/images/coldbrew-phucbontu.webp'},
    {id: 'coldbrew-suatuoi', category: 'cafe', title: 'Cold Brew Sữa Tươi', price: 45000, description: 'Thanh mát và cân bằng với hương vị cà phê nguyên bản 100% Arabica Cầu Đất cùng sữa tươi thơm béo cho từng ngụm tròn vị, hấp dẫn.', img: 'assets/images/coldbrew-suatuoi.webp'},
    {id: 'tradaocamsa-da', category: 'tea', title: 'Trà Đào Cam Sả Đá', price: 49000, description: 'Vị thanh ngọt của đào, vị chua dịu của Cam Vàng nguyên vỏ, vị chát của trà đen tươi được ủ mới mỗi 4 tiếng, cùng hương thơm nồng đặc trưng của sả chính là điểm sáng làm nên sức hấp dẫn của thức uống này.', img: 'assets/images/tradaocamsa-da.jpg'},
    {id: 'tradaocamsa-nong', category: 'tea', title: 'Trà Đào Cam Sả Nóng', price: 55000, description: 'Vị thanh ngọt của đào, vị chua dịu của Cam Vàng nguyên vỏ, vị chát của trà đen tươi được ủ mới mỗi 4 tiếng, cùng hương thơm nồng đặc trưng của sả chính là điểm sáng làm nên sức hấp dẫn của thức uống này.', img: 'assets/images/tradaocamsa-nong.webp'},
    {id: 'trahatsen-da', category: 'tea', title: 'Trà Hạt Sen Đá', price: 49000, description: 'Nền trà oolong hảo hạng kết hợp cùng hạt sen tươi, bùi bùi và lớp foam cheese béo ngậy. Trà hạt sen là thức uống thanh mát, nhẹ nhàng phù hợp cho cả buổi sáng và chiều tối.', img: 'assets/images/trahatsen-da.webp'},
    {id: 'trahatsen-nong', category: 'tea', title: 'Trà Hạt Sen Nóng', price: 55000, description: 'Nền trà oolong hảo hạng kết hợp cùng hạt sen tươi, bùi bùi thơm ngon. Trà hạt sen là thức uống thanh mát, nhẹ nhàng phù hợp cho cả buổi sáng và chiều tối.', img: 'assets/images/trahatsen-nong.webp'},
    {id: 'tralongnhanhatchia-da', category: 'tea', title: 'Trà Long Nhãn', price: 49000, description: 'Vị nhãn ngọt, tươi mát đặc trưng hoà quyện tinh tế cùng vị trà oolong hảo hạng và hạt chia mang đến cho bạn một thức uống không chỉ thơm ngon mà còn bổ dưỡng.', img: 'assets/images/tralongnhanhatchia-da.webp'},
    {id: 'tralongnhanhatchia-nong', category: 'tea', title: 'Trà Long Nhãn (Nóng)', price: 55000, description: 'Vị nhãn ngọt, tươi mát đặc trưng hoà quyện tinh tế cùng vị trà oolong hảo hạng và hạt chia mang đến cho bạn một thức uống không chỉ thơm ngon mà còn bổ dưỡng.', img: 'assets/images/tralongnhanhatchia-nong.webp'},
    {id: 'trasuachocolate-nong', category: 'tea', title: 'Trà Sữa Sô Cô La (Nóng)', price: 55000, description: 'Trong tiết trời se lạnh, còn gì tuyệt hơn khi được nhâm nhi ly Trà Sữa Sô Cô La ấm nóng. Hương vị trà Oolong nướng quen thuộc kết hợp cùng sô cô la ngọt ngào, thêm topping marshmallow mềm mịn, cứ uống là ghiền.', img: 'assets/images/trasuachocolate-nong.webp'},
    {id: 'trasuadua-nong', category: 'tea', title: 'Trà Sữa Dừa (Nóng)', price: 55000, description: 'Trà Sữa Dừa ấm nóng, xua tan lạnh lẽo hệt như cái ôm của người thương. Nền trà Oolong nướng đậm hương, êm dịu thêm chút sữa dừa thơm béo, ngọt ngào, tạo nên thức uống ngon khó cưỡng.', img: 'assets/images/trasuadua-nong.webp'},
    {id: 'traden-macchiato', category: 'tea', title: 'Trà Đen Macchiato', price: 55000, description: 'Trà đen được ủ mới mỗi ngày, giữ nguyên được vị chát mạnh mẽ đặc trưng của lá trà, phủ bên trên là lớp Macchiato "homemade" bồng bềnh quyến rũ vị phô mai mặn mặn mà béo béo.', img: 'assets/images/traden-macchiato.webp'},
    {id: 'hongtrasuachantrau', category: 'tea', title: 'Hồng Trà Sữa Trân Châu', price: 55000, description: 'Thêm chút ngọt ngào cho ngày mới với hồng trà nguyên lá, sữa thơm ngậy được cân chỉnh với tỉ lệ hoàn hảo, cùng trân châu trắng dai giòn có sẵn để bạn tận hưởng từng ngụm trà sữa ngọt ngào thơm ngậy thiệt đã.', img: 'assets/images/hongtrasuatranchau.webp'},
    {id: 'hongtrasua-nong', category: 'tea', title: 'Hồng Trà Sữa Nóng', price: 55000, description: 'Từng ngụm trà chuẩn gu ấm áp, đậm đà beo béo bởi lớp sữa tươi chân ái hoà quyện. Trà đen nguyên lá âm ấm dịu nhẹ, quyện cùng lớp sữa thơm béo khó lẫn - hương vị ấm áp chuẩn gu trà, cho từng ngụm nhẹ nhàng, ngọt dịu lưu luyến mãi nơi cuống họng.', img: 'assets/images/hongtrasua-nong.webp'},
    {id: 'trasuaoolongnuong-da', category: 'tea', title: 'Trà sữa Oolong Nướng', price: 55000, description: 'Hương vị chân ái đúng gu đậm đà với trà oolong được “sao” (nướng) lâu hơn cho hương vị đậm đà, hòa quyện với sữa thơm béo mang đến cảm giác mát lạnh, lưu luyến vị trà sữa đậm đà nơi vòm họng.', img: 'assets/images/trasuaoolongnuong-da.jpg'},
    {id: 'trasuaoolongnuong-nong', category: 'tea', title: 'Trà sữa Oolong Nóng', price: 55000, description: 'Đậm đà chuẩn gu và ấm nóng - bởi lớp trà oolong nướng đậm vị hoà cùng lớp sữa thơm béo. Hương vị chân ái đúng gu đậm đà - trà oolong được "sao" (nướng) lâu hơn cho vị đậm đà, hoà quyện với sữa thơm ngậy. Cho từng ngụm ấm áp, lưu luyến vị trà sữa đậm đà mãi nơi cuống họng.', img: 'assets/images/trasuaoolongnuong-nong.webp'},
    {id: 'trasuamacca-tranchau', category: 'tea', title: 'Trà Sữa Mắc Ca', price: 55000, description: 'Mỗi ngày với Tsunami Coffee sẽ là điều tươi mới hơn với sữa hạt mắc ca thơm ngon, bổ dưỡng quyện cùng nền trà oolong cho vị cân bằng, ngọt dịu đi kèm cùng Trân châu trắng giòn dai mang lại cảm giác “đã” trong từng ngụm trà sữa.', img: 'assets/images/trasuamacca-tranchau.webp'},
    {id: 'hongtra-lattemacchiato', category: 'tea', title: 'Hồng Trà Latte', price: 55000, description: 'Sự kết hợp hoàn hảo bởi hồng trà dịu nhẹ và sữa tươi, nhấn nhá thêm lớp macchiato trứ danh của Tsunami Coffee mang đến cho bạn hương vị trà sữa đúng gu tinh tế và healthy.', img: 'assets/images/hongtra-lattemacchiato.webp'},
    {id: 'hitea-phucbontu', category: 'tea', title: 'Hi Tea Phúc Bồn Tử', price: 49000, description: 'Nền trà Hibiscus thanh mát, quyện vị chua chua ngọt ngọt của phúc bồn tử 100% tự nhiên cùng quýt mọng nước mang đến cảm giác sảng khoái tức thì.', img: 'assets/images/hitea-phucbontu.webp'},
    {id: 'hitea-xoai', category: 'tea', title: 'Hi Tea Xoài Aloe Vera', price: 49000, description: 'Vị ngọt thanh, thơm phức từ xoài chín mọng kết hợp cùng vị chua đặc trưng của trà hoa Hibiscus tự nhiên, sẽ khiến bạn khó lòng quên được thức uống “chân ái” mùa hè này. Đặc biệt, topping Aloe Vera tự nhiên không chỉ nhâm nhi vui miệng mà còn giúp bạn “nâng tầm nhan sắc”.', img: 'assets/images/hitea-xoai.webp'},
    {id: 'hitea-dautayman', category: 'tea', title: 'HiTea Dâu Tây Mận', price: 49000, description: 'Sự kết hợp độc đáo giữa 3 sắc thái hương vị khác nhau: trà hoa Hibiscus chua thanh, Mận muối mặn mặn và Dâu tây tươi Đà Lạt cô đặc ngọt dịu. Ngoài ra, topping Aloe Vera tươi mát, ngon ngất ngây, đẹp đắm say, hứa hẹn sẽ khuấy đảo hè này.', img: 'assets/images/hitea-dautayman.jpg'},
    {id: 'hitea-yuzutranchau', category: 'tea', title: 'HiTea Yuzu Trân Châu', price: 49000, description: 'Không chỉ nổi bật với sắc đỏ đặc trưng từ trà hoa Hibiscus, Hi-Tea Yuzu còn gây ấn tượng với topping Yuzu (quýt Nhật) lạ miệng, kết hợp cùng trân châu trắng dai giòn sần sật, nhai vui vui.', img: 'assets/images/hitea-yuzutranchau.webp'},
    {id: 'hitea-vai', category: 'tea', title: 'HiTea Vải', price: 49000, description: 'Chút ngọt ngào của Vải, mix cùng vị chua thanh tao từ trà hoa Hibiscus, mang đến cho bạn thức uống đúng chuẩn vừa ngon, vừa healthy.', img: 'assets/images/hitea-vai.webp'},
    {id: 'hitea-dao', category: 'tea', title: 'HiTea Đào', price: 49000, description: 'Sự kết hợp ăn ý giữa Đào cùng trà hoa Hibiscus, tạo nên tổng thể hài hoà dễ gây “thương nhớ” cho team thích món thanh mát, có vị chua nhẹ.', img: 'assets/images/hitea-dao.jpg'},
    {id: 'hiteadatuyet-xoaidao', category: 'tea', title: 'HiTea Đá Tuyết Xoài Đào', price: 55000, description: 'Những miếng đào vàng ươm kết hợp với đá tuyết vị xoài mát lành, cùng nền trà hoa Hibiscus chua dịu đem đến cảm giác lạ miệng, hấp dẫn đến tận ngụm cuối cùng.', img: 'assets/images/hiteadatuyet-xoaidao.webp'},
    {id: 'hiteadatuyet-yuzuvai', category: 'tea', title: 'HiTea Đá Tuyết Yuzu Vải', price: 55000, description: 'Vị trà hoa Hibiscus chua chua, kết hợp cùng đá tuyết Yuzu mát lạnh tái tê, thêm miếng vải căng mọng, ngọt ngào sẽ khiến bạn thích thú ngay từ lần thử đầu tiên.', img: 'assets/images/hiteadatuyet-yuzuvai.webp'},
    {id: 'banhmique-ga', category: 'cake', title: 'Bánh Mì Gậy Gà', price: 25000, description: 'Phiên bản nâng cấp với trọng lượng tăng 80% so với bánh mì que thông thường, đem đến cho bạn bữa ăn nhanh gọn mà vẫn đầy đủ dinh dưỡng. Cắn một miếng là mê mẩn bởi vỏ bánh nướng giòn rụm, nhân đậm vị với từng miếng thịt gà mềm, ướp sốt kim quất chua ngọt, thơm nức đặc trưng. Càng "đúng bài" hơn khi thưởng thức kèm Cà phê đượm vị hoặc trà Hi-Tea thanh mát.', img: 'assets/images/banhmique-ga.jpg'},
    {id: 'banhmique-cangu', category: 'cake', title: 'Bánh Mì Gậy Cá Ngừ', price: 25000, description: 'Trọng lượng tăng 70% so với bánh mì que thông thường, thêm nhiều dinh dưỡng, thích hợp cho cả bữa ăn nhẹ lẫn ăn no. Ngon hết chỗ chê từ vỏ bánh nướng nóng giòn, cá ngừ đậm đà quyện lẫn sốt mayo thơm béo đến từng hạt bắp ngọt bùi hấp dẫn. Nhâm nhi bánh cùng ly Cà phê thơm nồng hay Hi-Tea tươi mát thì đúng chuẩn "điểm mười".', img: 'assets/images/banhmique-cangu.jpg'},
    {id: 'banhmique-pate', category: 'cake', title: 'Bánh Mì Que Pate', price: 15000, description: 'Vỏ bánh mì giòn tan, kết hợp với lớp nhân pate béo béo đậm đà sẽ là lựa chọn lý tưởng nhẹ nhàng để lấp đầy chiếc bụng đói , cho 1 bữa sáng - trưa - chiều - tối của bạn thêm phần thú vị.', img: 'assets/images/banhmique-pate.jpg'},
    {id: 'banhmique-patecay', category: 'cake', title: 'Bánh Mì Que Pate Cay', price: 15000, description: 'Vỏ bánh mì giòn tan, kết hợp với lớp nhân pate béo béo đậm đà và 1 chút cay cay sẽ là lựa chọn lý tưởng nhẹ nhàng để lấp đầy chiếc bụng đói , cho 1 bữa sáng - trưa - chiều - tối của bạn thêm phần thú vị.', img: 'assets/images/banhmique-patecay.webp'},
    {id: 'banhmithitnguoi', category: 'cake', title: 'Bánh Mì VN Thịt Nguội', price: 35000, description: 'Gói gọn trong ổ bánh mì Việt Nam là từng lớp chả, từng lớp jambon hòa quyện cùng bơ và pate thơm lừng, thêm dưa rau cho bữa sáng đầy năng lượng. *Phần bánh sẽ ngon và đậm đà nhất khi kèm pate. Để đảm bảo hương vị được trọn vẹn, Nhà mong bạn thông cảm vì không thể thay đổi định lượng pate.', img: 'assets/images/banhmithitnguoi.webp'},
    {id: 'croissant-trungmuoi', category: 'cake', title: 'Croissant trứng muối', price: 35000, description: 'Croissant trứng muối thơm lừng, bên ngoài vỏ bánh giòn hấp dẫn bên trong trứng muối vị ngon khó cưỡng.', img: 'assets/images/croissant-trungmuoi.webp'},
    {id: 'chabongphomai', category: 'cake', title: 'Chà Bông Phô Mai', price: 35000, description: 'Chiếc bánh với lớp phô mai vàng sánh mịn bên trong, được bọc ngoài lớp vỏ xốp mềm thơm lừng. Thêm lớp chà bông mằn mặn hấp dẫn bên trên.', img: 'assets/images/chabongphomai.jpg'},
    {id: 'mochi-phucbontu', category: 'cake', title: 'Mochi Kem Phúc Bồn Tử', price: 19000, description: 'Bao bọc bởi lớp vỏ Mochi dẻo thơm, bên trong là lớp kem lạnh cùng nhân phúc bồn tử ngọt ngào. Gọi 1 chiếc Mochi cho ngày thật tươi mát. Sản phẩm phải bảo quán mát và dùng ngon nhất trong 2h sau khi nhận hàng.', img: 'assets/images/mochi-phucbontu.webp'},
    {id: 'mochi-vietquat', category: 'cake', title: 'Mochi Kem Việt Quất', price: 19000, description: 'Bao bọc bởi lớp vỏ Mochi dẻo thơm, bên trong là lớp kem lạnh cùng nhân việt quất đặc trưng thơm thơm, ngọt dịu. Gọi 1 chiếc Mochi cho ngày thật tươi mát. Sản phẩm phải bảo quán mát và dùng ngon nhất trong 2h sau khi nhận hàng.', img: 'assets/images/mochi-vietquat.webp'},
    {id: 'mochi-dua', category: 'cake', title: 'Mochi Kem Dừa Dứa', price: 19000, description: 'Bao bọc bởi lớp vỏ Mochi dẻo thơm, bên trong là lớp kem lạnh cùng nhân dừa dứa thơm lừng lạ miệng. Gọi 1 chiếc Mochi cho ngày thật tươi mát. Sản phẩm phải bảo quán mát và dùng ngon nhất trong 2h sau khi nhận hàng.', img: 'assets/images/mochi-dua.webp'},
    {id: 'mochi-chocolate', category: 'cake', title: 'Mochi Kem Chocolate', price: 19000, description: 'Bao bọc bởi lớp vỏ Mochi dẻo thơm, bên trong là lớp kem lạnh cùng nhân chocolate độc đáo. Gọi 1 chiếc Mochi cho ngày thật tươi mát. Sản phẩm phải bảo quán mát và dùng ngon nhất trong 2h sau khi nhận hàng.', img: 'assets/images/mochi-chocolate.webp'},
    {id: 'mochi-matcha', category: 'cake', title: 'Mochi Kem Matcha', price: 19000, description: 'Bao bọc bởi lớp vỏ Mochi dẻo thơm, bên trong là lớp kem lạnh cùng nhân trà xanh đậm vị. Gọi 1 chiếc Mochi cho ngày thật tươi mát. Sản phẩm phải bảo quán mát và dùng ngon nhất trong 2h sau khi nhận hàng.', img: 'assets/images/mochi-matcha.webp'},
    {id: 'mochi-xoai', category: 'cake', title: 'Mochi Kem Xoài', price: 19000, description: 'Bao bọc bởi lớp vỏ Mochi dẻo thơm, bên trong là lớp kem lạnh cùng nhân xoài chua chua ngọt ngọt. Gọi 1 chiếc Mochi cho ngày thật tươi mát. Sản phẩm phải bảo quán mát và dùng ngon nhất trong 2h sau khi nhận hàng.', img: 'assets/images/mochi-xoai.webp'},
    {id: 'redvelvet', category: 'cake', title: 'Mousse Red Velvet', price: 35000, description: 'Bánh nhiều lớp được phủ lớp kem bên trên bằng Cream cheese.', img: 'assets/images/redvelvet.webp'},
    {id: 'mousse-gau', category: 'cake', title: 'Mousse Gấu Chocolate', price: 35000, description: 'Với vẻ ngoài đáng yêu và hương vị ngọt ngào, thơm béo nhất định bạn phải thử ít nhất 1 lần.', img: 'assets/images/mousse-gau.webp'},
    {id: 'khoga', category: 'snack', title: 'Gà Xé Lá Chanh', price: 25000, description: 'Thịt gà được xé tơi, mang hương vị mặn, ngọt, cay cay quyện nhau vừa chuẩn, thêm chút thơm thơm thơm từ lá chanh sấy khô giòn giòn xua tan ngay cơn buồn miệng.', img: 'assets/images/khoga.jpg'},
    {id: 'mitsay', category: 'snack', title: 'Mít Sấy', price: 20000, description: 'Mít sấy khô vàng ươm, giòn rụm, giữ nguyên được vị ngọt lịm của mít tươi.', img: 'assets/images/mitsay.jpg'},
    {id: 'cafe-rangxay-1000', category: 'home-cafe', title: 'Cà Phê Rang Xay Original 1 Túi 1KG', price: 235000, description: 'Cà phê Original 1 của Tsunami Coffee với 100% thành phần cà phê Robusta Đăk Lăk, vùng trồng cà phê ngon nhất Việt Nam. Bằng cách áp dụng kỹ thuật rang xay hiện đại, Cà phê Original 1 mang đến trải nghiệm tuyệt vời khi uống cà phê tại nhà với hương vị đậm đà truyền thống hợp khẩu vị của giới trẻ sành cà phê.', img: 'assets/images/cafe-rangxay-1000.jpg'},
    {id: 'cafe-hoatan-x40', category: 'hone-cafe', title: 'Cà Phê Hòa Tan Đậm Vị Việt Túi 40x16G', price: 99000, description: 'Bắt đầu ngày mới với tách cà phê sữa “Đậm vị Việt” mạnh mẽ sẽ giúp bạn luôn tỉnh táo và hứng khởi cho ngày làm việc thật hiệu quả.', img: 'assets/images/cafe-hoatan-x40.jpg'},
    {id: 'cafe-rangxay-250', category: 'home-cafe', title: 'Cà Phê Rang Xay Original 1 250g', price: 60000, description: 'Cà phê Original 1 của Tsunami Coffee với thành phần chính cà phê Robusta Đắk Lắk, vùng trồng cà phê nổi tiếng nhất Việt Nam. Bằng cách áp dụng kỹ thuật rang xay hiện đại, Cà phê Original 1 mang đến trải nghiệm tuyệt vời khi uống cà phê tại nhà với hương vị đậm đà truyền thống hợp khẩu vị của giới trẻ sành cà phê.', img: 'assets/images/cafe-rangxay-250.jpg'},
    {id: 'cafe-suada-x10', category: 'home-cafe', title: 'Cà Phê Sữa Đá Hòa Tan (10 gói x 22g)', price: 44000, description: 'Thật dễ dàng để bắt đầu ngày mới với tách cà phê sữa đá sóng sánh, thơm ngon như cà phê pha phin. Vị đắng thanh của cà phê hoà quyện với vị ngọt béo của sữa, giúp bạn luôn tỉnh táo và hứng khởi cho ngày làm việc thật hiệu quả.', img: 'assets/images/cafe-suada-x10.jpg'},
    {id: 'cafe-hoatan-x18', category: 'home-cafe', title: 'Cà Phê Hoà Tan Đậm Vị Việt (18 gói x 16 gam)', price: 48000, description: 'Bắt đầu ngày mới với tách cà phê sữa “Đậm vị Việt” mạnh mẽ sẽ giúp bạn luôn tỉnh táo và hứng khởi cho ngày làm việc thật hiệu quả.', img: 'assets/images/cafe-hoatan-x18.jpg'},
    {id: 'cafe-suada-x25', category: 'home-cafe', title: 'Cà Phê Sữa Đá Hòa Tan Túi 25x22G', price: 99000, description: 'Thật dễ dàng để bắt đầu ngày mới với tách cà phê sữa đá sóng sánh, thơm ngon như cà phê pha phin. Vị đắng thanh của cà phê hoà quyện với vị ngọt béo của sữa, giúp bạn luôn tỉnh táo và hứng khởi cho ngày làm việc thật hiệu quả.', img: 'assets/images/cafe-suada-x25.jpg'},
    {id: 'tradao-x14', category: 'home-tea', title: 'Trà Vị Đào Tearoma 14x14g', price: 32000, description: 'Được chiết xuất từ 100% trà tự nhiên, không phẩm màu tổng hợp, Trà vị Đào Tearoma mang đến cảm giác thanh mát cực đã. Nhấp một ngụm, cảm nhận trọn vị đào chua ngọt thơm ngon bùng nổ. Ngoài ra, trà còn bổ sung vitamin C cực kỳ có lợi cho sức khoẻ.', img: 'assets/images/tradao-x14.webp'},
    {id: 'trasua-tranchau-250', category: 'home-tea', title: 'Trà Sữa Trân Châu Tearoma 250g', price: 38000, description: 'Chỉ 2 phút có ngay ly Trà sữa trân châu ngon chuẩn vị quán. Thơm vị trà, béo vị sữa, cùng trân châu thật giòn dai sật sật. Đặc biệt, đây còn là thức uống tốt cho sức khoẻ nhờ thành phần 100% chiết xuất trà tự nhiên, không chất hoá học.', img: 'assets/images/trasua-tranchau-250.webp'},
    {id: 'tratacmatong-x14', category: 'home-tea', title: 'Trà Vị Tắc Mật Ong Tearoma 14x14g', price: 32000, description: 'Thổi bùng sảng khoái cùng Trà vị Tắc Mật Ong Tearoma không phẩm màu tổng hợp. Chiết xuất từ 100% trà tự nhiên, bổ sung vitamin C tốt cho sức khoẻ. Vị tắc chua chua hoà cùng mật ong ngọt dịu giúp bật vị giác, bừng vị mát tức thì.', img: 'assets/images/tratacmatong-x14.webp'},
    {id: 'traoolong-x20', category: 'home-tea', title: 'Trà Oolong Túi Lọc Tearoma 20x2G', price: 28000, description: 'Trà Oolong túi lọc với mùi hương dịu nhẹ hoàn toàn từ tự nhiên, vị hậu ngọt, và hương thơm tinh tế. Trà túi lọc Tearoma tiện lợi để sử dụng tại văn phòng, tại nhà,... nhưng vẫn đảm bảo được chất lượng về hương trà tinh tế, vị trà đậm đà.', img: 'assets/images/traoolong-x20.webp'},
    {id: 'tralai-x20', category: 'home-tea', title: 'Trà Lài Túi Lọc Tearoma 20x2G', price: 28000, description: 'Trà túi lọc Tearoma hương lài thơm tinh tế, thanh mát, trên nền trà xanh đậm đà khó quên. Trà túi lọc Tearoma tiện lợi để sử dụng tại văn phòng, tại nhà,.. nhưng vẫn đảm bảo được chất lượng về hương trà tinh tế, vị trà đậm đà.', img: 'assets/images/tralai-x20.webp'},
    {id: 'trasen-x20', category: 'home-tea', title: 'Trà Sen Túi Lọc Tearoma 20x2G', price: 28000, description: 'Trà túi lọc Tearoma hương sen tinh tế, thanh mát, trên nền trà xanh đậm đà khó quên. Trà túi lọc Tearoma tiện lợi để sử dụng tại văn phòng, tại nhà, đi du lịch,... nhưng vẫn đảm bảo được chất lượng về hương trà tinh tế, vị trà đậm đà.', img: 'assets/images/trasen-x20.webp'},
    {id: 'tradao-x20', category: 'home-tea', title: 'Trà Đào Túi Lọc Tearoma 20x2G', price: 28000, description: 'Trà túi lọc Tearoma hương đào với hương thơm tinh tế và hoàn toàn tự nhiên, cùng nền trà đen đậm vị khó quên. Trà túi lọc Tearoma tiện lợi để sử dụng tại văn phòng, tại nhà,.. nhưng vẫn đảm bảo được chất lượng về hương trà tinh tế, vị trà đậm đà.', img: 'assets/images/tradao-x20.webp'},
    {id: 'cloudtea-oolong-cheese', category: 'cloudtea', title: 'CloudTea Oolong Nướng Kem Cheese', price: '55000', description: 'Hội mê cheese sao có thể bỏ lỡ chiếc trà sữa siêu mlem này. Món đậm vị Oolong nướng - nền trà được yêu thích nhất hiện nay, quyện thêm kem sữa thơm béo. Đặc biệt, chinh phục ngay fan ghiền cheese bởi lớp foam phô mai mềm tan mằn mặn. Càng ngon cực với thạch Oolong nướng nguyên chất giòn dai nhai siêu thích.', img: 'assets/images/cloudtea-oolong-cheese.webp',},
    {id: 'cloudtea-oolong-caramel', category: 'cloudtea', title: 'CloudTea Oolong Nướng Caramel', price: '55000', description: 'Chiếc trà sữa chân ái dành cho tín đồ hảo ngọt gọi tên CloudTea Oolong Nướng Caramel. Sự kết hợp của foam trứng béo mịn, caramel thơm lừng, trà Oolong nướng rõ vị quyện kem sữa ngọt ngào, làm tan chảy vị giác tựa khoảnh khắc chạm môi người thương. Thêm bột cacao đậm đà và thạch Oolong nướng dai giòn giúp độ ngon nhân đôi.', img: 'assets/images/cloudtea-oolong-caramel.webp',},
    {id: 'cloudtea-hongtra', category: 'cloudtea', title: 'CloudTea Hồng Trà Arabica', price: '55000', description: 'Thức uống "chân ái" dành cho những ai vừa thích trà sữa ngọt ngào, êm dịu vừa mê cà phê đắng nhẹ, tỉnh táo. CloudTea Hồng Trà Arabica cực cuốn bởi lớp foam trứng bồng bềnh rắc thêm bột cacao thơm lừng. Vị thêm bùng nổ bởi sự kết hợp ăn ý giữa hồng trà đậm đà cùng cà phê Arabica êm vị. Món càng thêm hấp dẫn khi có thạch cà phê giòn, dai cực ngon.', img: 'assets/images/cloudtea-hongtra.webp',},
    {id: 'cloudtea-oolong-dua', category: 'cloudtea', title: 'CloudTea Oolong Nướng Kem Dừa Đá Xay', price: '55000', description: 'Trà sữa đá xay - phiên bản nâng cấp đầy mới lạ của trà sữa truyền thống, lần đầu xuất hiện tại Nhà. Ngon khó cưỡng với lớp kem dừa béo ngậy nhưng không ngấy, thêm vụn bánh quy phô mai giòn tan vui miệng. Trà Oolong nướng rõ hương đậm vị, quyện với sữa dừa beo béo, được xay mịn cùng đá, mát rượi trong tích tắc. Đặc biệt, thạch Oolong nướng nguyên chất giúp giữ trọn vị đậm đà của trà sữa đến giọt cuối cùng.', img: 'assets/images/cloudtea-oolong-dua.webp',},
  ];

  constructor(private route: ActivatedRoute) {
  }

  ngOnInit(){
    this.route.params.subscribe(params=>{
      this.cat = params['cat'];
    })
  }
}
